import Head from "next/head";
import { Inter } from "@next/font/google";
import Nav from "@/components/Nav";
import { useContext } from "react";
import { ThemeContext } from "@/ThemeContext";
import Main from "@/components/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const { theme, setTheme } = useContext(ThemeContext);

  const styles = {
    mainStyle: {background: `linear-gradient(45deg, ${theme?.bgPrimary}, ${theme?.bgSecondary})`},
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={styles.mainStyle}>
        <Nav />
        <Main/>
      </main>
    </>
  );
}
